// var superhero=["spiderman","ironman","flash","superman","captain Amrica","Thor","greenlantern","aquaman","doctor strange","black panther"]
// document.write(superhero);
// document.write("<br>");

// var hero= superhero.pop()
// document.write(hero);

function add(a,b,c,d){
    return(a+b);
}

function average(a,b,c,d){
    return add(a,b)/4;
}


function final_calculation(a,b,c,d){
    return average(a,b)-5;
}

var result=final_calculation(212453133424512,132453135);




document.write(result)










